In [1]:
# 데이터 프레임
import pandas as pd
import numpy as np

# 시각화
import matplotlib.pyplot as plt
import matplotlib
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 회귀 예측 모델
from statsmodels.api import Logit

# 사이킷런
## 데이터 정제
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split

## 분류 모델
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
### 분류-TREE
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from IPython.display import Image
import graphviz

## 그리드 서치
from sklearn.model_selection import GridSearchCV

## 평가
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report

# 
from subprocess import call

# 경고메시지 무시
import warnings
warnings.filterwarnings('ignore')

# 폰트 설정
matplotlib.rc("font", family = "NanumGothic")
matplotlib.rc("axes", unicode_minus=False)

In [3]:
df_2021_sales = pd.read_csv("cvs_data/data_result/2021_sales_v2.csv")
df_2022_sales = pd.read_csv("cvs_data/data_result/2022_sales_v2.csv")

df_sales = pd.concat([df_2021_sales,df_2022_sales])

df_sales['ItemNameCategory'] = df_sales['ItemNameLarge'] + '_'+df_sales['ItemNameMiddle']

df_ItemNameCategory_dummies = pd.get_dummies(df_sales['ItemNameCategory'])

df_sales_users = df_sales[['idUser','idPOS','SalesDate','SalesYear', 'SalesMonth', 'SalesDay', 'SalesWeekday', 'SalesTime', 'Gender', 'AgeGroup']]
df_sales_items =  df_sales[['idUser', 'idPOS', 'SalesDate', 'ItemId', 'Price']]

df_sales_items = pd.concat([df_sales_items, df_ItemNameCategory_dummies], axis=1)

# 같은 idUser, idPOS를 기준으로 중분류 dummy의 합
df_sales_itemsNprice_POS = pd.DataFrame(df_sales_items.groupby(['idUser', 'idPOS','SalesDate']).agg('sum')).reset_index()

df_sales_itemsNprice_POS = df_sales_itemsNprice_POS.merge(df_sales_users, on=['idUser', 'idPOS','SalesDate'], how='left').drop_duplicates()
display(df_sales_itemsNprice_POS)

df_sales_itemsNprice_POS.to_csv("cvs_data/data_result/users_itemsCategory.csv", index=False)

,idUser,idPOS,SalesDate,Price,간편식사_도시락,간편식사_샌드위치,간편식사_주먹밥,과자류_껌/초,과자류_빵/디,과자류_스낵,...,즉석조리_베이커,즉석조리_즉석커,즉석조리_튀김류,SalesYear,SalesMonth,SalesDay,SalesWeekday,SalesTime,Gender,AgeGroup
0,U100001,10004,2021-01-03,6500,0,0,0,0,0,0,...,0,0,0,2021,1,3,6,07:08:12,남성,40대
2,U100001,10006,2021-01-07,750,0,0,0,0,0,0,...,0,0,0,2021,1,7,3,00:42:18,남성,40대
3,U100001,10008,2021-01-10,1000,0,0,0,0,0,0,...,0,0,0,2021,1,10,6,18:16:24,남성,40대
4,U100277,10082,2022-04-12,1700,0,0,0,0,0,0,...,0,0,1,2022,4,12,1,11:59:22,여성,30대
5,U100277,10083,2022-04-14,2700,0,0,0,0,0,0,...,0,0,0,2022,4,14,3,01:34:37,여성,30대
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509289,U101098,10400,2021-12-31,1500,0,0,0,0,0,1,...,0,0,0,2021,12,31,4,00:26:40,남성,30대
509290,U101098,10402,2022-01-01,5300,0,0,0,0,1,1,...,0,0,0,2022,1,1,5,23:34:00,남성,30대
509292,U101098,10409,2022-01-08,19100,0,0,0,0,0,0,...,0,0,0,2022,1,8,5,02:29:40,남성,30대
509296,U101098,10410,2022-01-09,2500,0,0,0,0,0,1,...,0,0,0,2022,1,9,6,20:03:20,남성,30대
509298,U101098,10416,2022-01-14,4700,0,0,0,0,0,2,...,0,0,0,2022,1,14,4,05:25:20,남성,30대

In [6]:
df_sales_itemsNprice_POS.to_csv("CU_SOON/data/users_itemsCategory.csv", index=False)