In [91]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
from sklearn.tree import export_graphviz
import graphviz
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

matplotlib.rc("font", family = "Malgun Gothic")
matplotlib.rc("axes", unicode_minus = False)
pd.set_option('display.max_columns', 500)

In [92]:
df_raw = pd.read_csv("/home/piai/바탕화면/users_itemsCategory_v2.csv")
df_raw.head()

,idUser,idPOS,SalesDate,Price,간편식사_도시락,간편식사_샌드위치,간편식사_주먹밥,과자류_껌/초,과자류_빵/디,과자류_스낵,식품_가공식,식품_식재료,식품_안주류,아이스크_아이스,음료_아이스,음료_유제품,음료_음료,즉석조리_베이커,즉석조리_즉석커,즉석조리_튀김류,SalesYear,SalesMonth,SalesDay,SalesWeekday,SalesTime,Gender,AgeGroup
0,U100001,10004,2021-01-03,6500,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,2021,1,3,6,19:08:12,남성,40대
1,U100001,10006,2021-01-07,750,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2021,1,7,3,00:42:18,남성,40대
2,U100001,10008,2021-01-10,1000,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,2021,1,10,6,06:16:24,남성,40대
3,U100277,10082,2022-04-12,1700,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2022,4,12,1,23:59:22,여성,30대
4,U100277,10083,2022-04-14,2700,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2022,4,14,3,13:34:37,여성,30대

In [93]:
df_raw = pd.get_dummies(df_raw, columns = ["Gender", "AgeGroup"])
df_raw.head()

,idUser,idPOS,SalesDate,Price,간편식사_도시락,간편식사_샌드위치,간편식사_주먹밥,과자류_껌/초,과자류_빵/디,과자류_스낵,식품_가공식,식품_식재료,식품_안주류,아이스크_아이스,음료_아이스,음료_유제품,음료_음료,즉석조리_베이커,즉석조리_즉석커,즉석조리_튀김류,SalesYear,SalesMonth,SalesDay,SalesWeekday,SalesTime,Gender_남성,Gender_여성,AgeGroup_10대,AgeGroup_20대,AgeGroup_30대,AgeGroup_40대,AgeGroup_50대,AgeGroup_60대이상
0,U100001,10004,2021-01-03,6500,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,2021,1,3,6,19:08:12,1,0,0,0,0,1,0,0
1,U100001,10006,2021-01-07,750,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2021,1,7,3,00:42:18,1,0,0,0,0,1,0,0
2,U100001,10008,2021-01-10,1000,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,2021,1,10,6,06:16:24,1,0,0,0,0,1,0,0
3,U100277,10082,2022-04-12,1700,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2022,4,12,1,23:59:22,0,1,0,0,1,0,0,0
4,U100277,10083,2022-04-14,2700,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2022,4,14,3,13:34:37,0,1,0,0,1,0,0,0

In [94]:
df_weather_raw = pd.read_csv("/home/piai/바탕화면/weather_v3.csv")
df_weather_raw.head()

,dateObs,dateObs_y,dateObs_m,dateObs_d,TempAvg,TempMin,hhmiTempMin,TempMax,hhmiTempMax,hhmiTempMin_h,hhmiTempMin_m,hhmiTempMax_h,hhmiTempMax_m,classRainfall,hourRainfall,RainfallAmount,discomfortIndex,HumidAvg,SnowloadMax,hhmiSnowloadMax,hhmiSnowloadMax_h,hhmiSnowloadMax_m
0,2020-01-01,2020,1,1,-2.2,-6.5,00:01:00,0.3,14:57:00,0.0,1.0,14,57,약한비,9.83,0.1,전원쾌적,64.4,0.0,0.0,0.0,0.0
1,2020-01-02,2020,1,2,1.0,-0.7,00:01:00,3.8,15:00:00,0.0,1.0,15,0,무강수,0.00,0.0,전원쾌적,65.4,0.0,0.0,0.0,0.0
2,2020-01-03,2020,1,3,-0.1,-3.4,08:07:00,4.6,15:47:00,8.0,7.0,15,47,무강수,0.00,0.0,전원쾌적,56.9,0.0,0.0,0.0,0.0
3,2020-01-04,2020,1,4,1.2,-2.8,05:12:00,6.1,14:50:00,5.0,12.0,14,50,무강수,0.00,0.0,전원쾌적,50.8,0.0,0.0,0.0,0.0
4,2020-01-05,2020,1,5,1.3,-3.2,08:21:00,6.6,14:53:00,8.0,21.0,14,53,무강수,0.00,0.0,전원쾌적,45.6,0.0,0.0,0.0,0.0

In [95]:
df_raw.shape

(215618, 33)

In [96]:
df_weather_raw.shape

(1216, 22)

In [97]:
df_raw.SalesDate = pd.to_datetime(df_raw.SalesDate, format = "%Y-%m-%d")
df_weather_raw.dateObs = pd.to_datetime(df_weather_raw.dateObs, format = "%Y-%m-%d")

In [98]:
df_merged = pd.merge(df_raw, df_weather_raw, left_on='SalesDate', right_on='dateObs')

In [99]:
df_merged.shape

(215618, 55)

In [100]:
df_merged.head()

,idUser,idPOS,SalesDate,Price,간편식사_도시락,간편식사_샌드위치,간편식사_주먹밥,과자류_껌/초,과자류_빵/디,과자류_스낵,식품_가공식,식품_식재료,식품_안주류,아이스크_아이스,음료_아이스,음료_유제품,음료_음료,즉석조리_베이커,즉석조리_즉석커,즉석조리_튀김류,SalesYear,SalesMonth,SalesDay,SalesWeekday,SalesTime,Gender_남성,Gender_여성,AgeGroup_10대,AgeGroup_20대,AgeGroup_30대,AgeGroup_40대,AgeGroup_50대,AgeGroup_60대이상,dateObs,dateObs_y,dateObs_m,dateObs_d,TempAvg,TempMin,hhmiTempMin,TempMax,hhmiTempMax,hhmiTempMin_h,hhmiTempMin_m,hhmiTempMax_h,hhmiTempMax_m,classRainfall,hourRainfall,RainfallAmount,discomfortIndex,HumidAvg,SnowloadMax,hhmiSnowloadMax,hhmiSnowloadMax_h,hhmiSnowloadMax_m
0,U100001,10004,2021-01-03,6500,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,2021,1,3,6,19:08:12,1,0,0,0,0,1,0,0,2021-01-03,2021,1,3,-5.6,-9.1,05:36:00,-2.0,12:38:00,5.0,36.0,12,38,무강수,0.0,0.0,전원쾌적,45.0,0.0,0.0,0.0,0.0
1,U100281,10009,2021-01-03,4000,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,2021,1,3,6,10:00:00,0,1,0,0,0,1,0,0,2021-01-03,2021,1,3,-5.6,-9.1,05:36:00,-2.0,12:38:00,5.0,36.0,12,38,무강수,0.0,0.0,전원쾌적,45.0,0.0,0.0,0.0,0.0
2,U100285,10012,2021-01-03,1200,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,2021,1,3,6,09:14:12,1,0,0,0,0,1,0,0,2021-01-03,2021,1,3,-5.6,-9.1,05:36:00,-2.0,12:38:00,5.0,36.0,12,38,무강수,0.0,0.0,전원쾌적,45.0,0.0,0.0,0.0,0.0
3,U100290,10009,2021-01-03,13600,0,0,0,0,0,0,3,0,0,0,0,0,1,0,0,0,2021,1,3,6,14:35:33,1,0,0,0,0,1,0,0,2021-01-03,2021,1,3,-5.6,-9.1,05:36:00,-2.0,12:38:00,5.0,36.0,12,38,무강수,0.0,0.0,전원쾌적,45.0,0.0,0.0,0.0,0.0
4,U100291,10007,2021-01-03,6050,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,2021,1,3,6,21:02:26,1,0,0,0,1,0,0,0,2021-01-03,2021,1,3,-5.6,-9.1,05:36:00,-2.0,12:38:00,5.0,36.0,12,38,무강수,0.0,0.0,전원쾌적,45.0,0.0,0.0,0.0,0.0

In [101]:
df_merged.columns

Index(['idUser', 'idPOS', 'SalesDate', 'Price', '간편식사_도시락', '간편식사_샌드위치',
       '간편식사_주먹밥', '과자류_껌/초', '과자류_빵/디', '과자류_스낵', '식품_가공식', '식품_식재료',
       '식품_안주류', '아이스크_아이스', '음료_아이스', '음료_유제품', '음료_음료', '즉석조리_베이커',
       '즉석조리_즉석커', '즉석조리_튀김류', 'SalesYear', 'SalesMonth', 'SalesDay',
       'SalesWeekday', 'SalesTime', 'Gender_남성', 'Gender_여성', 'AgeGroup_10대',
       'AgeGroup_20대', 'AgeGroup_30대', 'AgeGroup_40대', 'AgeGroup_50대',
       'AgeGroup_60대이상', 'dateObs', 'dateObs_y', 'dateObs_m', 'dateObs_d',
       'TempAvg', 'TempMin', 'hhmiTempMin', 'TempMax', 'hhmiTempMax',
       'hhmiTempMin_h', 'hhmiTempMin_m', 'hhmiTempMax_h', 'hhmiTempMax_m',
       'classRainfall', 'hourRainfall', 'RainfallAmount', 'discomfortIndex',
       'HumidAvg', 'SnowloadMax', 'hhmiSnowloadMax', 'hhmiSnowloadMax_h',
       'hhmiSnowloadMax_m'],
      dtype='object')

df_merged = df_merged[['Price', '간편식사_도시락', '간편식사_샌드위치',
       '간편식사_주먹밥', '과자류_껌/초', '과자류_빵/디', '과자류_스낵', '식품_가공식', '식품_식재료',
       '식품_안주류', '아이스크_아이스', '음료_아이스', '음료_유제품', '음료_음료', '즉석조리_베이커',
       '즉석조리_즉석커', '즉석조리_튀김류', 'SalesMonth', 'Gender_남성', 'Gender_여성', 'AgeGroup_10대',
       'AgeGroup_20대', 'AgeGroup_30대', 'AgeGroup_40대', 'AgeGroup_50대',
       'AgeGroup_60대이상','TempAvg','RainfallAmount','HumidAvg']]
df_merged.head()

In [102]:
df_merged = df_merged.groupby(["idUser","SalesMonth"]).sum()
df_merged

/tmp/ipykernel_22550/4161268891.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_merged = df_merged.groupby(["idUser","SalesMonth"]).sum()

                     idPOS   Price  간편식사_도시락  간편식사_샌드위치  간편식사_주먹밥  과자류_껌/초  \
idUser  SalesMonth
U100001 1            30018    8250         0          0         0        0
U100277 4           100933   47600         0          1         0        0
        5           162009  138600         0          2         1        6
        6           193156  127150         1          0         0        2
        7           244897  248800         0          1         1       11
...                    ...     ...       ...        ...       ...      ...
U101098 8           296054  222100         2          3         1        4
        9           286865  175250         2          0         2        7
        10          266766  232140         4          1         2       10
        11          360188  272630         3          6         0        5
        12          196407  152300         2          2         1        7

                    과자류_빵/디  과자류_스낵  식품_가공식  식품_식재료  식품_안주류  아이스크_아이스  음료_아이스  \
idUser  SalesMonth
U100001 1                 0       0       1       1       0         0       1
U100277 4                 3       1       4       1       1         0       0
        5                 3       4       8       8       3         3       2
        6                 6       3      10       3       5         3       2
        7                12       8      10      12       4         6       1
...                     ...     ...     ...     ...     ...       ...     ...
U101098 8                10       1      14      16       5         5       0
        9                 5       8       9       7       3         4       1
        10                8       9      12       8       5         1       0
        11                4       6      16      10       6         5       1
        12                9       5       6       7       3         2       0

                    음료_유제품  음료_음료  즉석조리_베이커  즉석조리_즉석커  즉석조리_튀김류  SalesYear  \
idUser  SalesMonth
U100001 1                1      0         0         0         0       6063
U100277 4                0      1         1         0         1      20220
        5                0      7         1         0         2      32352
        6                1      7         0         0         0      38418
        7                1      4         0         0         1      48528
...                    ...    ...       ...       ...       ...        ...
U101098 8                4     13         0         0         0      58619
        9                1      9         1         0         1      56596
        10               0      6         1         0         1      52556
        11               4      7         2         0         2      70748
        12               1      4         1         0         0      38404

                    SalesDay  SalesWeekday  Gender_남성  Gender_여성  \
idUser  SalesMonth
U100001 1                 20            15          3          0
U100277 4                215            28          0         10
        5                284            49          0         16
        6                326            58          0         19
        7                343            65          0         24
...                      ...           ...        ...        ...
U101098 8                457            73         29          0
        9                418            76         28          0
        10               461            73         26          0
        11               606            87         35          0
        12               305            49         19          0

                    AgeGroup_10대  AgeGroup_20대  AgeGroup_30대  AgeGroup_40대  \
idUser  SalesMonth
U100001 1                      0             0             0             3
U100277 4                      0             0            10             0
        5                      0             0            16             0
        6                      0             0            19             0
        7                      0             0            24             0
...                          ...           ...           ...           ...
U101098 8                      0             0            29             0
        9                      0             0            28             0
        10                     0             0            26             0
        11                     0             0            35             0
        12                     0             0            19             0

                    AgeGroup_50대  AgeGroup_60대이상  dateObs_y  dateObs_m  \
idUser  SalesMonth
U100001 1                      0               0       6063          3
U100277 4                      0               0      20220         40
        5                      0               0      32352         80
        6                      0               0      38418        114
        7                      0               0      48528        168
...                          ...             ...        ...        ...
U101098 8                      0               0      58619        232
        9                      0               0      56596        252
        10                     0               0      52556        260
        11                     0               0      70748        385
        12                     0               0      38404        228

                    dateObs_d  TempAvg  TempMin  TempMax  hhmiTempMin_h  \
idUser  SalesMonth
U100001 1                  20    -27.8    -38.4    -13.1           18.0
U100277 4                 215    157.8    120.6    206.5           95.0
        5                 284    325.7    242.4    422.7          144.0
        6                 326    443.4    387.5    515.8          172.0
        7                 343    651.4    577.6    737.7          207.0
...                       ...      ...      ...      ...            ...
U101098 8                 457    744.3    665.7    842.0          253.0
        9                 418    621.8    516.8    741.7          243.0
        10                461    382.2    281.8    510.1          284.0
        11                606    268.5    126.7    436.3          361.0
        12                305    -33.1   -110.1     53.7          238.0

                    hhmiTempMin_m  hhmiTempMax_h  hhmiTempMax_m  hourRainfall  \
idUser  SalesMonth
U100001 1                    76.0             26             45          0.00
U100277 4                   308.0            138            292         25.00
        5                   526.0            220            587          2.33
        6                   600.0            274            430        104.66
        7                   609.0            339            746         78.05
...                           ...            ...            ...           ...
U101098 8                   849.0            395            729        102.07
        9                   947.0            397            757         92.00
        10                  901.0            346            695         30.41
        11                 1178.0            448           1000         35.75
        12                  687.0            232            488         12.77

                    RainfallAmount  HumidAvg  SnowloadMax  hhmiSnowloadMax  \
idUser  SalesMonth
U100001 1                      0.0     149.3          4.0              2.0
U100277 4                     17.3     608.9          0.0              0.0
        5                      1.5     941.5          0.0              0.0
        6                    200.1    1460.2          0.0              0.0
        7                    156.6    1856.5          0.0              0.0
...                            ...       ...          ...              ...
U101098 8                    184.0    2231.5          0.0              0.0
        9                    223.6    2031.7          0.0              0.0
        10                    17.3    1765.2          0.0              0.0
        11                    54.2    2251.1          0.0              0.0
        12                     6.4    1120.2          5.0              3.0

                    hhmiSnowloadMax_h  hhmiSnowloadMax_m
idUser  SalesMonth
U100001 1                         0.0                2.0
U100277 4                         0.0                0.0
        5                         0.0                0.0
        6                         0.0                0.0
        7                         0.0                0.0
...                               ...                ...
U101098 8                         0.0                0.0
        9                         0.0                0.0
        10                        0.0                0.0
        11                        0.0                0.0
        12                        0.0                3.0

[9724 rows x 46 columns]

In [45]:
df_merged.to_csv("/home/piai/바탕화면/data_for_modeling_v1.csv")